"""empty message

Revision ID: 7fdcffc2ca4b
Revises: 
Create Date: 2025-02-04 21:43:43.204581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdcffc2ca4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_kodu', sa.String(length=50), nullable=True),
    sa.Column('kullanici_adi', sa.String(length=64), nullable=False),
    sa.Column('sifre_hash', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('rehber_id', sa.Integer(), nullable=True),
    sa.Column('ogretmen_id', sa.Integer(), nullable=True),
    sa.Column('sinif', sa.String(length=10), nullable=True),
    sa.Column('okul_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['rehber_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('deneme_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('dogru_matematik', sa.Integer(), nullable=True),
    sa.Column('yanlis_matematik', sa.Integer(), nullable=True),
    sa.Column('net_matematik', sa.Float(), nullable=True),
    sa.Column('dogru_fen', sa.Integer(), nullable=True),
    sa.Column('yanlis_fen', sa.Integer(), nullable=True),
    sa.Column('net_fen', sa.Float(), nullable=True),
    sa.Column('dogru_turkce', sa.Integer(), nullable=True),
    sa.Column('yanlis_turkce', sa.Integer(), nullable=True),
    sa.Column('net_turkce', sa.Float(), nullable=True),
    sa.Column('dogru_sosyal', sa.Integer(), nullable=True),
    sa.Column('yanlis_sosyal', sa.Integer(), nullable=True),
    sa.Column('net_sosyal', sa.Float(), nullable=True),
    sa.Column('dogru_ingilizce', sa.Integer(), nullable=True),
    sa.Column('yanlis_ingilizce', sa.Integer(), nullable=True),
    sa.Column('net_ingilizce', sa.Float(), nullable=True),
    sa.Column('dogru_din', sa.Integer(), nullable=True),
    sa.Column('yanlis_din', sa.Integer(), nullable=True),
    sa.Column('net_din', sa.Float(), nullable=True),
    sa.Column('toplam_net', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gunluk_veriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('namaz', sa.Integer(), nullable=True),
    sa.Column('kuran', sa.Integer(), nullable=True),
    sa.Column('matematik', sa.Integer(), nullable=True),
    sa.Column('fen', sa.Integer(), nullable=True),
    sa.Column('turkce', sa.Integer(), nullable=True),
    sa.Column('sosyal', sa.Integer(), nullable=True),
    sa.Column('ingilizce', sa.Integer(), nullable=True),
    sa.Column('din', sa.Integer(), nullable=True),
    sa.Column('kitap_okuma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ogrenci_id', 'tarih', name='unique_ogrenci_tarih')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gunluk_veriler')
    op.drop_table('deneme_sonuclari')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
